[project]
name = "etl-sandbox"
version = "0.1.0"
description = "ETL project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "snowflake-connector-python",
]

[tool.uv]
package = true

[project.scripts]
check-connection = "etl.connection:check_connection"
